name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend image
        run: |
          docker build -t ghcr.io/khanyisov/jobtracker-backend:latest .
          docker push ghcr.io/khanyisov/jobtracker-backend:latest

      - name: Build & push frontend image
        run: |
          docker build -t ghcr.io/khanyisov/jobtracker-frontend:latest ./job-app-tracker-frontend
          docker push ghcr.io/khanyisov/jobtracker-frontend:latest

      # ADD THESE STEPS:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart Frontend Web App
        run: |
          az webapp restart --name jobtracker-frontend --resource-group jobtracker-rg

      - name: Restart Backend Web App
        run: |
          az webapp restart --name jobtracker-backend-f7bxc9fyg4htendh --resource-group jobtracker-rg